//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteBanCaCanhKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HangHoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HangHoa()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public int MaHang { get; set; }
        public string TenHang { get; set; }
        public string TenNSX { get; set; }
        public Nullable<int> MaLoaiHang { get; set; }
        public string TenLoaiHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonViTinh { get; set; }
        public Nullable<double> Gia { get; set; }
        public string Anh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual LoaiHangHoa LoaiHangHoa { get; set; }
    }
}
